import { 
  SET_VIEW_SELECTED_STRAIN, TOGGLE_WALK_INTO_TROPHY_ROOM, WHICH_IMAGE_INCREMENT, WHICH_IMAGE_DECREMENT, SET_CURTAIN_IMAGE_CLICK,
  SET_OUTER_PHOTO_INDEX, NESTED_PHOTO_INCREMENT, NESTED_PHOTO_DECREMENT, NESTED_PHOTO_RESET, NESTED_PHOTO_LENGTH_END, PHOTO_ARRAY_INDEX_PUSH, PHOTO_ARRAY_INDEX_VISITED_RESET,

  SET_STARS_RANDOM_USER, SET_STARS, SET_STARS_ARRAY, RESET_STARS_ARRAY,
  INCREMENT_VIDEO_SRC_ARRAY, RESET_VIDEO_SRC_ARRAY
} from 'redux/trophyRoom/trophyRoomSlice';

export {
  SET_VIEW_SELECTED_STRAIN, TOGGLE_WALK_INTO_TROPHY_ROOM, WHICH_IMAGE_INCREMENT, WHICH_IMAGE_DECREMENT, SET_CURTAIN_IMAGE_CLICK,
  SET_OUTER_PHOTO_INDEX, NESTED_PHOTO_INCREMENT, NESTED_PHOTO_DECREMENT, NESTED_PHOTO_RESET, NESTED_PHOTO_LENGTH_END, PHOTO_ARRAY_INDEX_PUSH, PHOTO_ARRAY_INDEX_VISITED_RESET,

  SET_STARS_RANDOM_USER, SET_STARS, SET_STARS_ARRAY, RESET_STARS_ARRAY,
  INCREMENT_VIDEO_SRC_ARRAY, RESET_VIDEO_SRC_ARRAY
 };


