import { 
    SET_SEE_LOGIN_OR_SIGNUP, SET_LOGIN_EMAIL_INPUT, SET_LOGIN_PASSWORD_INPUT, TOGGLE_LOGIN_PASSWORD_INPUT_SEE_TEXT,
    SET_SIGNUP_USERNAME_INPUT, SET_SIGNUP_EMAIL_INPUT, SET_SIGNUP_AGE_INPUT, SET_SIGNUP_PASSWORD_INPUT, SET_CHECKED,
    TOGGLE_PASSWORD_UPPERCASE, TOGGLE_PASSWORD_SPECIAL_CHAR, TOGGLE_PASSWORD_LENGTH_PASS, TOGGLE_PASSWORD_NUMBER_CHAR, TOGGLE_PASSWORD_TOO_EZ,
    TOGGLE_SIGNUP_PASSWORD_SEE,

    TOGGLE_EMAIL_UNIQUE, TOGGLE_EMAIL_EXTENSION, SET_EMAIL_EXTENSION_UI,
    TOGGLE_USERNAME_UNIQUE, TOGGLE_USERNAME_LENGTH, TOGGLE_SUCCESSFUL_LOGIN, TOGGLE_REMEMBER_ME_USER,
    INCREMENT_INCORRECT_LOGIN_ATTEMPT, RESET_INCORRECT_LOGIN_ATTEMPT
} from 'redux/loginSignup/loginSignupSlice';

export {
    SET_SEE_LOGIN_OR_SIGNUP, SET_LOGIN_EMAIL_INPUT, SET_LOGIN_PASSWORD_INPUT, TOGGLE_LOGIN_PASSWORD_INPUT_SEE_TEXT,
    SET_SIGNUP_USERNAME_INPUT, SET_SIGNUP_EMAIL_INPUT, SET_SIGNUP_AGE_INPUT, SET_SIGNUP_PASSWORD_INPUT, SET_CHECKED,
    TOGGLE_PASSWORD_UPPERCASE, TOGGLE_PASSWORD_SPECIAL_CHAR, TOGGLE_PASSWORD_LENGTH_PASS, TOGGLE_PASSWORD_NUMBER_CHAR, TOGGLE_PASSWORD_TOO_EZ,
    TOGGLE_SIGNUP_PASSWORD_SEE,

    TOGGLE_EMAIL_UNIQUE, TOGGLE_EMAIL_EXTENSION, SET_EMAIL_EXTENSION_UI,
    TOGGLE_USERNAME_UNIQUE, TOGGLE_USERNAME_LENGTH, TOGGLE_SUCCESSFUL_LOGIN, TOGGLE_REMEMBER_ME_USER,
    INCREMENT_INCORRECT_LOGIN_ATTEMPT, RESET_INCORRECT_LOGIN_ATTEMPT
 };


