import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Axios from 'axios'
import APIcall from '../utility/APIcall'

export default function Home() {
  console.log('hey whats up')
  const checkAPI = async () => {
    console.log('functionality linked')    
    await APIcall('all', null)
  }
  checkAPI()

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
    <main className={styles.main}>
        <h1> 
        hey 
      </h1>
    </main>

    </div>
  )
}
